### ISSUE TITLE
uninitialized constant Page

### ISSUE THREAD

**Issue by pbmolini** [thoughtbot/high_voltage#192] opened 2015-04-01 21:31 UTC
I have followed the guide up to the **Specifying a root path** section but, when I try it both on `root_path` and on `/pages/landing`, I got this error:

`NameError - uninitialized constant Page:`

My ruby version is 2.2.0 and I have

```ruby
# config/initializers/high_voltage.rb
HighVoltage.configure do |config|
  config.home_page = 'landing'
  config.route_drawer = HighVoltage::RouteDrawers::Root
end

# config/routes.rb
 get 'pages/landing' => 'high_voltage/pages#show', id: 'landing'

# Gemfile
gem 'rails', '4.2.0'
gem 'high_voltage', '~> 2.2.1'
```

Of course I have also `app/views/pages/landing.html.erb`

**Comment by dgalarza** [comment] 2015-04-03 18:15
Hi @pbmolini, sorry to hear your having trouble. Unfortunately I wasn't able to reproduce the error your getting. Can you provide more of the stack trace that your getting back?

**Comment by pbmolini** [comment] 2015-04-09 08:16
Hi @dgalarza, 
here is the stack trace
```
10:12:25 web.1  | NameError - uninitialized constant Page:
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/dependencies.rb:533:in `load_missing_constant'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/dependencies.rb:184:in `const_missing'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/inflector/methods.rb:261:in `block in constantize'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/inflector/methods.rb:259:in `constantize'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
10:12:25 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:151:in `resource_class'
10:12:25 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:158:in `resource_class_with_parent'
10:12:25 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:41:in `authorize_resource'
10:12:25 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:443:in `block in make_lambda'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
10:12:25 web.1  |   actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
10:12:25 web.1  |   activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
10:12:25 web.1  |   actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
10:12:25 web.1  |   actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
10:12:25 web.1  |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/etag.rb:24:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/head.rb:13:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
10:12:25 web.1  |   rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
10:12:25 web.1  |   better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
10:12:25 web.1  |   better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   web-console (2.1.1) lib/web_console/middleware.rb:37:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
10:12:25 web.1  |   railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
10:12:25 web.1  |   railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/runtime.rb:18:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/lock.rb:17:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   railties (4.2.0) lib/rails/engine.rb:518:in `call'
10:12:25 web.1  |   railties (4.2.0) lib/rails/application.rb:164:in `call'
10:12:25 web.1  |   newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/lock.rb:17:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/content_length.rb:15:in `call'
10:12:25 web.1  |   rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
10:12:25 web.1  |    () usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
10:12:25 web.1  |    () usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
10:12:25 web.1  |    () usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

and here are the request params (using gem `better_errors`):
`{"id"=>"landing", "controller"=>"high_voltage/pages", "action"=>"show"}`

Please tell me if you need more info
Thanks

Pietro

**Comment by pbmolini** [comment] 2015-04-16 19:56
If it can help, the same happens with Rails 4.2.1 and ruby 2.2.0

```
Parameters: {"id"=>"landing"}
21:53:47 web.1  | Completed 500 Internal Server Error in 24ms (ActiveRecord: 0.0ms)
21:53:47 web.1  |
21:53:47 web.1  | NameError - uninitialized constant Page:
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/dependencies.rb:533:in `load_missing_constant'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/dependencies.rb:184:in `const_missing'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/inflector/methods.rb:261:in `block in constantize'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/inflector/methods.rb:259:in `constantize'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
21:53:47 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:151:in `resource_class'
21:53:47 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:158:in `resource_class_with_parent'
21:53:47 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:41:in `authorize_resource'
21:53:47 web.1  |   cancancan (1.10.1) lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:448:in `block in make_lambda'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `block in call'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:504:in `call'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
21:53:47 web.1  |   actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
21:53:47 web.1  |   activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
21:53:47 web.1  |   actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
21:53:47 web.1  |   actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
21:53:47 web.1  |   warden (1.2.3) lib/warden/manager.rb:34:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/etag.rb:24:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/head.rb:13:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
21:53:47 web.1  |   rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
21:53:47 web.1  |   better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
21:53:47 web.1  |   better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
21:53:47 web.1  |   railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
21:53:47 web.1  |   railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/runtime.rb:18:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/lock.rb:17:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   railties (4.2.1) lib/rails/engine.rb:518:in `call'
21:53:47 web.1  |   railties (4.2.1) lib/rails/application.rb:164:in `call'
21:53:47 web.1  |   newrelic_rpm (3.11.2.286) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/lock.rb:17:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/content_length.rb:15:in `call'
21:53:47 web.1  |   rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
21:53:47 web.1  |    () usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
21:53:47 web.1  |    () usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
21:53:47 web.1  |    () usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

**Comment by aaronsama** [comment] 2015-04-16 21:35
h2. Incompatibility with CanCanCan

It appears that there is an incompatibility with [CanCanCan](https://github.com/CanCanCommunity/cancancan). The `check_authorization` method in `ApplicationController` looks for the Pages model no matter what.
Adding `authorize_resource class: false` to the PagesController does not solve the issue and neither does `skip_authorization_check` or `skip_load_and_authorize_resource`.

@pbmolini and I managed to solve the issue by adding the following to ApplicationController

```ruby
class ApplicationController < ActionController::Base

  ...
  
  authorize_resource unless: :devise_or_pages_controller?
  check_authorization unless: :devise_or_pages_controller?

  ...

  private

  def devise_or_pages_controller?
    devise_controller? || is_a?(PagesController)
  end
end

**Comment by dgalarza** [comment] 2015-04-17 14:37
Thanks @aaronsama. Closing this since its outside of `HighVoltage`'s scope.

**Closed by dgalarza** 2015-04-17 14:37 UTC

**Comment by mrjlynch** [comment] 2016-11-22 00:31
I tweaked @aaronsama private method above to get thinks working: 

```ruby
def devise_or_pages_controller?
    devise_controller? || is_a?(HighVoltage::PagesController)
end
```

**Comment by marcamillion** [comment] 2017-01-24 21:22
@mrjlynch & @aaronsama How did you handle non logged in users? i.e. do your static pages show up for both logged in and logged out users? If so, how did you enable it for the latter?

**Comment by marcamillion** [comment] 2017-01-25 07:35
Nevermind, I got it. Thanks.
